In [8]:
import torch

In [5]:
a = torch.zeros(2,3)
print("a: \n", a)

b = torch.ones([2,3])
print("b: \n", b)

c = torch.rand((2,3))
print("c: \n", c)

a: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
b: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
c: 
 tensor([[0.8207, 0.1044, 0.5107],
        [0.3239, 0.3607, 0.1266]])



# Autograd computation : A small example

In [12]:
BATCH_SIZE = 16
INPUT_SIZE = 1000
HIDDEN_SIZE = 100
OUTPUT_SIZE = 10 

class TinyModel(torch.nn.Module):
    def __init__(self):
        super(TinyModel, self).__init__()

        self.layer1 = torch.nn.Linear(1000,100)
        self.relu   = torch.nn.ReLU()
        self.layer2 = torch.nn.Linear(100,10) 

    def forward(self, x):
        x = self.layer1(x)
        x = self.relu(x)
        x = self.layer2(x) 

        return x

some_input = torch.rand(BATCH_SIZE , INPUT_SIZE, requires_grad = True) 
ideal_output = torch.rand(BATCH_SIZE, OUTPUT_SIZE, requires_grad = False)

model = TinyModel()


In [51]:
#Constants 

input_tensor = torch.unsqueeze(torch.tensor([1, 0, 1, 0 , 1, 1, 0, 1, 1, 1], dtype = float) , 0)

print("input_tensor shape", input_tensor.size())
print("input_tensor : \n" , input_tensor) 
weight_matrix = torch.rand((10,2) , dtype = float)
print("weight matrix : \n", weight_matrix)


y_true = torch.tensor([1, 0]) 
print("y_true : ", y_true)
y_pred = torch.squeeze(torch.matmul(input_tensor, weight_matrix), 0)
print("y_pred shape", y_pred.size()) 
print("y_pred iteration_1 : ", y_pred)
print()

error_1 = ((y_true[0] - y_pred[0])**2 + (y_true[1] - y_pred[1])**2 ) / 2
print("error 1 ", error_1)

input_tensor shape torch.Size([1, 10])
input_tensor : 
 tensor([[1., 0., 1., 0., 1., 1., 0., 1., 1., 1.]], dtype=torch.float64)
weight matrix : 
 tensor([[0.1555, 0.5518],
        [0.1344, 0.8719],
        [0.7431, 0.6012],
        [0.9479, 0.9600],
        [0.5439, 0.9675],
        [0.0911, 0.7084],
        [0.2318, 0.4510],
        [0.1819, 0.6513],
        [0.9049, 0.1394],
        [0.3129, 0.8420]], dtype=torch.float64)
y_true :  tensor([1, 0])
y_pred shape torch.Size([2])
y_pred iteration_1 :  tensor([2.9332, 4.4616], dtype=torch.float64)

error 1  tensor(11.8214, dtype=torch.float64)


The Loss : 

$$
MSE = \frac{1}{n} \sum_{i=1}^{n} (y_i - \hat{y}_i)^2
$$